services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app_network
    command: bash -c "uv sync && uv run python app/prestart.py && uv run fastapi run app/main.py --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15-alpine
    container_name: fastapi-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: fastapi-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fastapi-worker
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      - api
      - redis
      - db
    networks:
      - app_network
    command: uv run celery -A app.core.celery_app worker --loglevel=info

  beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fastapi-beat
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      - api
      - redis
      - db
    networks:
      - app_network
    command: uv run celery -A app.core.celery_app beat --loglevel=info

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
