apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: fastapi-app-prod

patches:
  - path: patch-replicas.yaml

# Add suffixes if needed or image tags
images:
  - name: fastapi-app
    newTag: stable
